version: '3'
services:
  video_transcode:
    container_name: cloudcats-video-transcode
    build: .
    networks:
      - cloudcats
    volumes:
      - /Users/rory/University/fourth_year/cloud/docker_stuff/data:/app/fs
      - ./:/app
      - /app/node_modules
networks:
  cloudcats:
    external:
      name: cloudcats