version: '3'
services:
  web:
    container_name: cloudcats-web
    build: .
    ports:
      - 3000:80
    networks:
      - cloudcats
    volumes:
      - /Users/rory/University/fourth_year/cloud/docker_stuff/data:/app/static/fs
      - ./:/app
      - /app/node_modules
    environment:
      - IS_DEBUG=false
      - S3_ADDR=172.18.0.11
      - RABBIT_ADDR=172.18.0.10
      - REDIS_ADDR=172.18.0.12
      - DATA_SERVICE=minio
networks:
  cloudcats:
    external:
      name: cloudcats