FROM bamos/openface
WORKDIR /app
COPY . /app
RUN pip install --upgrade urllib3
RUN pip install -r requirements.txt
RUN pip install --upgrade pyOpenSSL ndg-httpsclient pyasn1
ENTRYPOINT python worker.py